[project]
name = "plastron-repo"
description = "High-level classes and functions for interacting with a Fedora repository"
authors = [
    { name='University of Maryland Libraries', email='lib-ssdr@umd.edu' },
    { name='Josh Westgard', email='westgard@umd.edu' },
    { name='Peter Eichman', email='peichman@umd.edu' },
    { name='Mohamed Abdul Rasheed', email='mohideen@umd.edu' },
    { name='Ben Wallberg', email='wallberg@umd.edu' },
    { name='David Steelman', email='dsteelma@umd.edu' },
    { name='Marc Andreu Grillo Aguilar', email='aguilarm@umd.edu' },
]
readme = "README.md"
requires-python = ">= 3.8"
dependencies = [
    "bagit~=1.8",
    "beautifulsoup4~=4.12",
    "paramiko~=3.4",
    "plastron-client",
    "plastron-messaging",
    "plastron-models",
    "plastron-utils",
    "pysolr~=3.9",
    "PyYAML~=6.0",
    "rdflib~=6.3",
    "requests~=2.32",
    "URLObject~=2.4",
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "freezegun~=1.5",
    "pytest~=8.3",
    "pytest-cov~=5.0",
    "pytest-datadir~=1.5",
]

[build-system]
requires = ["setuptools>=66.1.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { "file" = "VERSION" }
